import {afterEach,expect,it} from "vitest";
import {buildApp} from "./app.js";
const apps: ReturnType<typeof buildApp>[]=[];
afterEach(async()=>{for(const app of apps.splice(0))await app.close();});
async function fixture(){const app=buildApp({secretCodec:{seal:value=>value,unseal:value=>value}});apps.push(app);
  const baseline=(await app.inject({method:"PUT",url:"/api/settings/provider",payload:{kind:"ollama",baseUrl:"http://localhost:9999/v1",model:"original",apiKey:"key",temperature:1,maxTokens:1024}})).json();
  return {app,baseline,patch:(values:Record<string,unknown>,expected=baseline)=>app.inject({method:"PATCH",url:"/api/settings/provider/extension-patch",payload:{values,baseline:expected}})};}
it("updates only requested provider fields and preserves credentials",async()=>{const {app,baseline,patch}=await fixture();
  const result=await patch({model:"changed",maxTokens:2048});expect(result.statusCode,result.body).toBe(200);
  expect(result.json()).toMatchObject({conflicts:[],provider:{model:"changed",maxTokens:2048,baseUrl:baseline.baseUrl,temperature:1,hasApiKey:true}});
  expect((await app.inject({method:"GET",url:"/api/settings/provider"})).json().model).toBe("changed");
});
it("accepts the original Helper's unlocked context limit through both save paths",async()=>{
  const {app,baseline,patch}=await fixture();
  const expanded=await patch({contextLimitTokens:2_000_000});
  expect(expanded.statusCode,expanded.body).toBe(200);
  expect(expanded.json().provider.contextLimitTokens).toBe(2_000_000);
  const saved=await app.inject({method:"PUT",url:"/api/settings/provider",payload:{...baseline,contextLimitTokens:2_000_000}});
  expect(saved.statusCode,saved.body).toBe(200);
  expect((await app.inject({method:"GET",url:"/api/settings/provider"})).json().contextLimitTokens).toBe(2_000_000);
});
it("preserves newer provider edits field by field while applying unrelated queued fields",async()=>{const {app,baseline,patch}=await fixture();
  await app.inject({method:"PUT",url:"/api/settings/provider",payload:{...baseline,model:"newer-native"}});
  const result=await patch({model:"stale-extension",maxTokens:3072});
  expect(result.json().conflicts).toEqual(["model"]);expect(result.json().provider).toMatchObject({model:"newer-native",maxTokens:3072});
});
it("invalid parameters do not partially update the provider and absent baselines cannot clobber settings",async()=>{const {app,patch}=await fixture();
  const invalid=await patch({model:"invalid-batch",temperature:99});expect(invalid.statusCode).toBe(400);
  expect((await app.inject({method:"GET",url:"/api/settings/provider"})).json().model).toBe("original");
  expect((await patch({baseUrl:"file:///invalid"})).statusCode).toBe(400);
  const stale=await patch({model:"no-baseline"},{});expect(stale.json()).toMatchObject({conflicts:["model"],provider:{model:"original"}});
});
